/*
** EPITECH PROJECT, 2025
** docker_api.c
** File description:
** This code is used to make a request to the Docker API
** It was been generated by an AI (ChatGPT)
*/
#include "docker.h"

void generate_ports_boucle(int ports[], int count,
    struct json_object *port_bindings)
{
    struct json_object *host_port_array;
    struct json_object *host_port;
    char *host_port_str;
    char *port_key;

    for (int i = 0; i < count; i += 2) {
        host_port_array = json_object_new_array();
        host_port = json_object_new_object();
        host_port_str = GC_MALLOC((int_len(ports[i + 1]) + 1) * sizeof(char));
        snprintf(host_port_str, (int_len(ports[i + 1]) + 1) * sizeof(char),
        "%d", ports[i + 1]);
        json_object_object_add(host_port, "HostPort",
            json_object_new_string(host_port_str));
        json_object_array_add(host_port_array, host_port);
        port_key = GC_MALLOC((int_len(ports[i]) + 5) * sizeof(char));
        snprintf(port_key, int_len(ports[i]) + 5, "%d/tcp", ports[i]);
        json_object_object_add(port_bindings, port_key, host_port_array);
    }
}

struct json_object *generate_ports_config(int ports[], int count)
{
    struct json_object *port_bindings = json_object_new_object();

    if (count % 2 != 0) {
        fprintf(stderr, "Erreur: 209\n");
        json_object_put(port_bindings);
        return NULL;
    }
    generate_ports_boucle(ports, count, port_bindings);
    return port_bindings;
}

void generate_exposed_ports_boucle(int ports[], int count,
    struct json_object *exposed_ports)
{
    char *port_key;

    for (int i = 0; i < count; i += 2) {
        port_key = GC_MALLOC((int_len(ports[i]) + 5) * sizeof(char));
        snprintf(port_key, int_len(ports[i]) + 5, "%d/tcp", ports[i]);
        json_object_object_add(exposed_ports,
            port_key, json_object_new_object());
    }
}

struct json_object *generate_exposed_ports_config(int ports[], int count)
{
    struct json_object *exposed_ports = json_object_new_object();

    if (count % 2 != 0) {
        fprintf(stderr, "Erreur : 120\n");
        json_object_put(exposed_ports);
        return NULL;
    }
    generate_exposed_ports_boucle(ports, count, exposed_ports);
    return exposed_ports;
}

char *generate_config(char *image, int ports[], int port_count, char *name)
{
    char *config_str;
    char *result;
    struct json_object *config = json_object_new_object();
    struct json_object *host_config = json_object_new_object();
    struct json_object *port_bindings = generate_ports_config(
        ports, port_count);
    struct json_object *exposed_ports = generate_exposed_ports_config(
        ports, port_count);

    json_object_object_add(config, "Image", json_object_new_string(image));
    json_object_object_add(host_config, "PortBindings", port_bindings);
    json_object_object_add(config, "HostConfig", host_config);
    json_object_object_add(config, "ExposedPorts", exposed_ports);
    json_object_object_add(config, "name", json_object_new_string(name));
    config_str = (char *)json_object_to_json_string(config);
    result = GC_STRDUP(config_str);
    if (!result)
        return NULL;
    json_object_put(config);
    return result;
}
