/*
** EPITECH PROJECT, 2025
** docker_api.c
** File description:
** This code is used to make a request to the Docker API
** It was been generated by an AI (ChatGPT)
*/
#include "docker.h"

bool allow_more_space(char **json, size_t *json_size)
{
    char *buffer = *json;
    char *new_json = NULL;

    if (strlen(*json) + strlen(buffer) + 2 > *json_size) {
        *json_size *= 2;
        new_json = (char *)GC_REALLOC(*json, *json_size);
        if (!new_json) {
            perror("Erreur de réallocation mémoire");
            return false;
        }
        *json = new_json;
    }
    return true;
}

int int_len(long long int nb)
{
    int count = 0;

    if (nb == 0) {
        return 1;
    }
    if (nb < 0) {
        count++;
        nb = -nb;
    }
    while (nb > 0) {
        nb = nb / 10;
        count++;
    }
    return count;
}
